### ISSUE TITLE
Detect authentication failure

### ISSUE THREAD

**Issue by toff63** [signalfx/signalfx-python#28]
Hello,

The following snippet doesn't raise any error while the token is invalid:

``` python
import signalfx
sfx = signalfx.SignalFx().ingest('fake')
sfx.send(gauges=[{'metric': 'fake-metric', 'value' :  1, 'dimensions': {'host':'127.0.0.1'}}])
sfx.stop()
```

I suspect the thread actually sending the metric fails. However, I couldn't find a way with the current library API to retrieve this error.

**Comment by mpetazzoni** [comment]
Hi,

Thanks for your feedback. There is indeed no way right now to tell. We'll work on adding a callback mechanism to let the user know if the token is or becomes invalid (ie. when the requests made by the send thread start getting 401 return codes).

**Comment by diegopacheco** [comment]
@mpetazzoni 

IF I generate the token via the link:  *Generate User API Access Token* It simply does not work and I get no errors. If I use the link on Access Tokens -> New Token. My metrics is being registered but my data is not there. 

This is the python code I'm using it:
```python
import signalfx
import atexit
import time

sfx = signalfx.SignalFx().ingest('MY_TOKEN')
try:
    sfx.send(
        gauges=[
        ],
        counters=[
          { 'metric': 'test.py.int',
            'value': 1600,
            'timestamp': int(time.time()) }
        ],
        cumulative_counters=[]
    )
finally:
    atexit.register(sfx.stop)
print "done " + str(int(time.time()))

```

**Comment by mdubbyap** [comment]
Hi @diegopacheco , sorry that is a bit confusing and we're working on making it less so.  The tokens under "Generate User API Access Token" are temporary tokens for talking with api.signalfx.com.  For ingestion you found the right ones under "Access Tokens".  

The reason your sample program isn't working is the timestamp is sent in milliseconds since epoch not seconds as python's time.time() function returns.  If you simply multiply by 1000 or omit it  completely and they will get the timestamp at the moment of ingestion. An example can be found at https://github.com/signalfx/signalfx-python/blob/master/examples/generic_usecase.py

Hope this helps.  Thanks for the question!

matthew.

**Comment by MovieStoreGuy** [comment]
A work around I have seen our company do is provide a bot accounts username and password as environment variables use this api: https://developers.signalfx.com/sessiontokens_reference.html#operation/Create%20Session%20Token
to constantly update the session token.

Granted we have to wait for a 401 from the api to do this action but is trivial to implement :)
