### ISSUE TITLE
SignalFx client not reporting failure when token has exceeded quota

### ISSUE THREAD

**Issue by JDusub83** [signalfx/signalfx-python#81]
I have been streaming data to SignalFx using `client = SignalFx().ingest('some_token')`.

Unbeknownst to me, the token exceeded its quota, and new metrics were not being uploaded.  When using `client.send()` and then viewing `response.ok` ([source](https://github.com/signalfx/signalfx-python/blob/master/signalfx/ingest.py#L251)), it was `True`, even though the data was not entering SignalFx.  In my eyes, this is a silent failure.

I ultimately figured out the root cause of the token having hit its quota.  Is there some way to have the SignalFx client report that the given token is at its quota's limit?

**Comment by mpetazzoni** [comment]
Because of the asynchronous nature of some of the ingest processes (creation of new timeseries for example) that happen on the SignalFx side and the fact that some of the received data batch may be accepted, but not all, it's unfortunately not practical to have a meaningful response status code on our ingest API other than for direct authentication errors (invalid, missing or expired tokens).
